# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import re
import shutil
import sys

# sphinx_multiversion builds every ref with the configuration of the ref that triggered the run,
# and only the documentation sources come from the ref being built. Resolving the package next to
# those sources instead of next to this file makes autodoc import the code of the ref being built,
# so the API reference of a tag describes the release that carries it.
_MULTIVERSION_SOURCEDIR = os.environ.get("SPHINX_MULTIVERSION_SOURCEDIR")

basedir = os.path.abspath(os.path.join(_MULTIVERSION_SOURCEDIR or os.path.dirname(__file__), "..", "..", "src"))
sys.path.insert(0, basedir)
import matchcake

_html_folders_formatted = {}
_allowed_special_methods = ["__init__", "__call__"]

_GITHUB_MATH_FENCE = re.compile(r"^```math[ \t]*\n(.*?)\n^```[ \t]*$", re.DOTALL | re.MULTILINE)
_GITHUB_INLINE_MATH = re.compile(r"\$`([^`\n]+?)`\$")
_VERSION_COMPONENT = re.compile(r"\d+")


def skip(app, what, name, obj, would_skip, options):
    if name in _allowed_special_methods:
        return False
    return would_skip


def github_math_to_myst(app, docname, source):
    """
    Rewrite GitHub-flavored math delimiters to MyST dollarmath before parsing.

    The markdown sources under ``docs/`` use GitHub-flavored math so they render on
    github.com: inline math is wrapped in ``$`...`$`` and display math in ```` ```math ````
    fences, both of which keep the LaTeX literal and protect it from GitHub's markdown
    sanitizer. MyST's dollarmath expects ``$...$`` and ``$$...$$`` instead, so this handler
    converts the GitHub forms in place when Sphinx reads each source.
    """
    text = source[0]
    text = _GITHUB_MATH_FENCE.sub(lambda match: "$$\n" + match.group(1) + "\n$$", text)
    text = _GITHUB_INLINE_MATH.sub(lambda match: "$" + match.group(1) + "$", text)
    source[0] = text


def drop_mathjax3_config(app):
    """
    Drop the MathJax configuration generated by ``myst_parser``, which this theme cannot render.

    ``myst_parser`` fills ``mathjax3_config`` so that MathJax only looks at the elements it marked,
    which makes ``sphinx.ext.mathjax`` ship that configuration as a script asset carrying a body
    instead of a file name. The ``karma_sphinx_theme`` layout renders every script asset as
    ``<script src="...">`` and ignores the body, so the asset becomes a link to a file named
    ``None`` that answers 404 on every page carrying it. ``_templates/layout.html`` already writes
    the same ``window.MathJax`` object by hand, so nothing is lost by dropping the generated one.
    The handler is connected with a priority above the default that ``myst_parser`` registers with,
    so it always runs after the value ``myst_parser`` sets.

    Without a generated configuration ``sphinx.ext.mathjax`` loads MathJax with ``async`` instead
    of ``defer``; the theme drops both attributes, so the emitted tag stays the same.
    """
    app.config.mathjax3_config = None


def _version_sort_key(name: str) -> tuple:
    """
    Order a version by the numbers it holds rather than by its characters.

    :param name: name of the git ref a version was built from.
    :return: the numbers of the name, in order, so that ``0.10.0`` sorts above ``0.2.0``.
    :rtype: tuple
    """
    return tuple(int(component) for component in _VERSION_COMPONENT.findall(name))


def name_version_after_ref(app, config):
    """
    Label a version built from a tag with the name of that tag.

    ``sphinx_multiversion`` reads the configuration of every ref in the process that launches the
    builds, and copies the ``version`` it finds there over ``config.version`` on ``config-inited``.
    That value comes from ``importlib.metadata``, which answers with the version installed in the
    environment, so a tag would otherwise carry the version of the ref that triggered the run. This
    handler is connected with a priority above the one ``sphinx_multiversion`` registers with, so it
    always runs after the value it sets.
    """
    metadata = getattr(config, "smv_metadata", None) or {}
    current_version = getattr(config, "smv_current_version", "")
    if metadata.get(current_version, {}).get("source") != "tags":
        return
    config.version = current_version
    config.release = current_version


def order_versions(app, pagename, templatename, context, doctree):
    """
    Order the entries of the version selector: the branches first, then the tags, newest first.

    ``sphinx_multiversion`` hands the template a mapping whose order follows the refs as git lists
    them, which sorts ``0.10.0`` below ``0.2.0``. The handler is connected with a priority above the
    one ``sphinx_multiversion`` registers with, so the mapping it builds is already in the context.
    """
    versions = context.get("versions")
    if versions is None:
        return
    context["ordered_versions"] = list(versions.branches) + sorted(
        versions.tags, key=lambda version: _version_sort_key(version.name), reverse=True
    )


def setup(app):
    # sphinx.ext.mathjax only loads MathJax on a page whose own document holds math, so a page
    # that merely quotes a math-bearing section title, such as the toctree of theory.rst, would
    # show the LaTeX source of that title instead of the formula.
    app.set_html_assets_policy("always")
    app.connect("builder-inited", drop_mathjax3_config, priority=800)
    app.connect("config-inited", name_version_after_ref, priority=800)
    app.connect("source-read", github_math_to_myst)
    app.connect("autodoc-skip-member", skip)
    app.connect("html-page-context", change_pathto)
    app.connect("html-page-context", order_versions, priority=800)
    app.connect("build-finished", move_private_folders)


def change_pathto(app, pagename, templatename, context, doctree):
    """
    Replace pathto helper to change paths to folders with a leading underscore.
    """
    pathto = context.get("pathto")

    def gh_pathto(otheruri, *args, **kw):
        if otheruri.startswith("_"):
            otheruri_fmt = otheruri[1:]
            _html_folders_formatted[os.path.dirname(otheruri)] = os.path.dirname(otheruri_fmt)
        else:
            otheruri_fmt = otheruri
        return pathto(otheruri_fmt, *args, **kw)

    context["pathto"] = gh_pathto


def move_private_folders(app, e):
    """
    Remove leading underscore from folders in the output folder.
    """

    def join(dir):
        return os.path.join(app.builder.outdir, dir)

    for item in os.listdir(app.builder.outdir):
        if item.startswith("_") and os.path.isdir(join(item)) and item in _html_folders_formatted:
            shutil.move(join(item), join(item[1:]))


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "MatchCake"
copyright = matchcake.__copyright__.replace("Copyright ", "")
author = matchcake.__author__
version = matchcake.__version__

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.githubpages",
    # 'sphinx_rtd_theme',
    "sphinxcontrib.bibtex",
    "myst_nb",
    "sphinx.ext.mathjax",
    # 'sphinx.ext.mathbase',
    "sphinx.ext.todo",
    "sphinx_multiversion",
]

smv_branch_whitelist = r"^(main|dev)$"
# Release tags only: a pre-release such as 0.0.4-beta1 is left out of the version selector.
# sphinx_multiversion reads the conf.py of every ref it selects before building it, and drops the
# ref when that read fails, so a tag whose sources no longer import under the dependencies pinned
# today is skipped with a "Failed load config" line in the build log instead of failing the run.
smv_tag_whitelist = r"^\d+\.\d+\.\d+$"
smv_remote_whitelist = r"^origin$"
smv_released_pattern = r"^refs/tags/.*$"
smv_outputdir_format = "{ref.name}"
smv_prefer_remote_refs = True

nb_execution_mode = "off"

myst_enable_extensions = ["dollarmath", "colon_fence"]

bibtex_bibfiles = ["references.bib"]

templates_path = ["_templates"]
exclude_patterns = ["tutorials/README.md"]

suppress_warnings = ["myst.header"]


# -- Options for the linkcheck builder ---------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder

linkcheck_retries = 3
linkcheck_timeout = 30
linkcheck_ignore = [
    # GitHub answers 404 to unauthenticated clients on this path.
    r"https://github\.com/MatchCake/MatchCake/stargazers",
    # Links into this repository's own tree cannot be resolved over HTTP from a pull request that
    # adds or moves the file they point to, because the branch only gains it once the pull request
    # is merged. The .github/scripts/resolve_repository_links.py script, run by the Link-Check job
    # of .github/workflows/docs.yml, checks these against the checkout instead. Sphinx matches an
    # entry against the start of the link, so the trailing "." keeps a link that names a branch
    # without a path out of the entry: that link has nothing to resolve on disk and is still
    # checked over HTTP.
    r"https://github\.com/MatchCake/MatchCake/(blob|tree)/[^/]+/.",
]
linkcheck_anchors_ignore = [
    # The default of Sphinx: an anchor that a script builds once the page is loaded.
    "^!",
    # GitHub serves only the first page of a long issue thread, so the comment that an anchor names
    # is missing from the answer even though a browser reaches it. The page itself is still checked.
    r"^issuecomment-\d+$",
    # IOPscience builds the abstract of an article in the browser, so its anchor is missing too.
    "^artAbst$",
]


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "karma_sphinx_theme"
html_theme_options = {"navigation_depth": 2}
html_static_path = ["_static"]
# html_css_files = [
#     'css/float_right.css',
# ]
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
latex_engine = "xelatex"
latex_elements = {
    "preamble": r"\usepackage{physics}"
    r"\usepackage{mathtools}"
    r"\usepackage{amsmath}"
    r"\usepackage{nicefrac}"
}
